apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: unit-keyvault
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: nginx-cert
    type: kubernetes.io/tls
    data:
    - objectName: sampleapp
      key: tls.key
    - objectName: sampleapp
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "unit-keyvault"
    objects: |
      array:
        - |
          objectName:               
          objectType: secret
          objectVersion: ""
    tenantId: "6099438d-7a33-4ed0-807b-f9a89c5225c7"